import { v7 as uuidv7 } from 'uuid';

// UUIDv7 generated by the application, never SQL's @default (see the ERD);
// order matters because a product's cover is its first image by ascending
// id, and that would break with UUIDv4.
export const newId = (): string => uuidv7();

// Converts "15m" or "7d" to milliseconds: TTLs live in the environment as a
// string because @nestjs/jwt consumes them that way, but expires_at is a
// date column and needs the number.
export function parseDuration(value: string): number {
  const match = /^(\d+)(s|m|h|d)$/.exec(value.trim());

  if (!match) {
    throw new Error(
      `Invalid duration: "${value}". Expected format: 30s, 15m, 12h or 7d.`,
    );
  }

  const amount = Number(match[1]);
  const unit = match[2] as 's' | 'm' | 'h' | 'd';
  const factor = { s: 1000, m: 60_000, h: 3_600_000, d: 86_400_000 }[unit];

  return amount * factor;
}
